# Generated by Django 2.2.4 on 2019-09-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', 'Por hacer'), ('1', 'Haciendo'), ('2', 'Hecho')], default='0', max_length=1, verbose_name='status'),
        ),
    ]
